# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(max_length=200)),
                ('output_files', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('num_input_params', models.IntegerField(default=0)),
                ('authorized_groups', models.CharField(default='guest', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_params', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('finished', 'Finished')], max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('api_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.API')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
